networks:
  nexorder-network:
services:
  nexordersproductssql:
    container_name: nexordersproductssql
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=db_password
    ports:
      - 1433:1433
    volumes:
      - nexordersproductssql_data:/var/opt/mssql
    networks:
      - nexorder-network

  nexorder.productservice:
    container_name: nexorderproductservice
    # image: mitanshu5/mitanshu-patel:nexorderproductservice-1.0
    image: nexorderproductservice:1.1
    build:
      context: .
      dockerfile: NexOrder.ProductService/Dockerfile
    ports:
      - 7023:80
    environment:
      - DB_SERVER_NAME=db_server
      - DB_NAME=db_name
      - DB_PASSWORD=db_password
      - ConnectionStrings:connection_string
      - RunMigration=true
    depends_on:
      - nexordersproductssql
    networks:
      - nexorder-network

volumes:
  nexordersproductssql_data:
    driver: local
