networks:
  nexorder-network:
services:
  nexordersproductssql:
    container_name: nexordersproductssql
    image: mcr.microsoft.com/mssql/server:2019-latest
    env_file:
      - local.env
    ports:
      - 1434:1433
    volumes:
      - nexordersproductssql_data:/var/opt/mssql
    networks:
      - nexorder-network

  nexorderredis:
    container_name: nexorderredis
    image: redis:7-alpine
    ports:
      - 6379:6379
    networks:
      - nexorder-network

  nexorder.productservice:
    container_name: nexorderproductservice
    # image: mitanshu5/mitanshu-patel:nexorderproductservice-1.0
    image: nexorderproductservice:1.1
    build:
      context: .
      dockerfile: NexOrder.ProductService/Dockerfile
      args:
        # comes from .env file as follows, is mainly for custom package nuget source:
        # GITHUB_USERNAME=github_username
        # GITHUB_TOKEN=github_token
        - GITHUB_USERNAME=$GITHUB_USERNAME
        - GITHUB_TOKEN=$GITHUB_TOKEN
    ports:
      - 7023:80
    env_file:
      - local.env
      # Following config will be needed in local.env file:-
      # DB_SERVER_NAME=nexordersproductssql
      # ACCEPT_EULA=Y
      # SA_PASSWORD=db_password
      # DB_NAME=db_name
      # DB_PASSWORD=db_password!
      # ConnectionStrings__ServiceBusConnectionString=connectionstring_for_servicebus
      # RunMigration=true
      # APPLICATIONINSIGHTS_CONNECTION_STRING=connectionstring_for_application_insights
      # RedisCacheOptions_Configuration=<<redis-url>>
      # RedisCacheOptions_InstanceName=<<instance-name>>
      # OpenAIAPIKey=<<api-key>>
      # OpenAIDeployment=<<deployment-name>>
      # OpenAIEndpoint=<<endpoint-url>>
      # OpenAIModel=<<model-name>>
    depends_on:
      - nexordersproductssql
      - nexorderredis
    networks:
      - nexorder-network

volumes:
  nexordersproductssql_data:
    driver: local
