networks:
  nexorder-network:
services:
  nexordersproductssql:
    container_name: nexordersproductssql
    image: mcr.microsoft.com/mssql/server:2019-latest
    env_file:
      - local.env
    ports:
      - 1434:1433
    volumes:
      - nexordersproductssql_data:/var/opt/mssql
    networks:
      - nexorder-network

  nexorderredis:
    container_name: nexorderredis
    image: redis:7-alpine
    ports:
      - 6379:6379
    networks:
      - nexorder-network

  nexorder.productservice:
    container_name: nexorderproductservice
    # image: mitanshu5/mitanshu-patel:nexorderproductservice-1.0
    image: nexorderproductservice:1.1
    build:
      context: .
      dockerfile: NexOrder.ProductService/Dockerfile
    ports:
      - 7023:80
    env_file:
      - local.env
      # Following config will be needed in local.env file:-
        # DB_SERVER_NAME=nexordersproductssql
        # ACCEPT_EULA=Y
        # SA_PASSWORD=db_password
        # DB_NAME=db_name
        # DB_PASSWORD=db_password!
        # ConnectionStrings__ServiceBusConnectionString=connectionstring_for_servicebus
        # RunMigration=true
    depends_on:
      - nexordersproductssql
      - nexorderredis
    networks:
      - nexorder-network

volumes:
  nexordersproductssql_data:
    driver: local
