# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - NexOrder-ProductService

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to container registry
        uses: docker/login-action@v2
        with:
          registry: practiceregistry.azurecr.io/
          username: ${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_2959A89C0D0A4FC2B31CBE1BBA5C0B32 }}
          password: ${{ secrets.AZUREAPPSERVICE_CONTAINERPASSWORD_39A2E5B57DF245A0A8E15F296F5BB2D1 }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: practiceregistry.azurecr.io/${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_2959A89C0D0A4FC2B31CBE1BBA5C0B32 }}/nexorderproductserviceapp:${{ github.sha }}
          file: NexOrder.ProductService/Dockerfile
          build-args: |
            GITHUB_USERNAME=${{ github.repository_owner }}
            GITHUB_TOKEN=${{ secrets.NUGET_TOKEN }}

  migrate:
   runs-on: ubuntu-latest
   needs: build
   steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup .NET 8
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Install dotnet-ef (global)
      run: |
        dotnet tool install --global dotnet-ef --version 8.0.*
        echo "$HOME/.dotnet/tools" >> $GITHUB_PATH

    - name: Run EF Core migrations
      env:
        DB_CONNECTION: ${{ secrets.SQL_CONN }}
      run: |
        dotnet ef database update \
          --project NexOrder.ProductService.Infrastructure \
          --startup-project NexOrder.ProductService.Infrastructure \
          --connection "$DB_CONNECTION"

  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    needs: build
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_0DBB8C878FB24A6A85FF81E5728F10F4 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_ACBEA1A314EC4A5F96A1B487B3C9B5B9 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_4C0CA2FE46C54F599541AADF6C4DE73D }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'NexOrder-ProductService'
          slot-name: 'Production'
          images: 'practiceregistry.azurecr.io/${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_2959A89C0D0A4FC2B31CBE1BBA5C0B32 }}/nexorderproductserviceapp:${{ github.sha }}'

